### ISSUE TITLE
Guidebook

### ISSUE THREAD

**Issue by sir-pinecone** [ruby0x1/machinery_blog_archive#1]
Hey, thanks for this. There's also a guidebook that you may want to include. I'm linking to the most recent capture https://web.archive.org/web/20220127004837/https://ourmachinery.com/files/guidebook.md.html

**Comment by ruby0x1** [comment]
fwiw I don't want to mirror all of their content in relation to the engine.
The blog was a public facing thing vs the guidebook being part of the docs specifically.
I had a local copy and added it before realizing it wasn't on the main path for the public blog, so I removed it again.

**Comment by sir-pinecone** [comment]
Sounds good! Cheers
